services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_NAME: clonebox
      DB_USER: web
    secrets:
      - db_password
      - web_llm_api_key
    volumes:
      - web_fileShare:/clonebox/uploads
    networks:
      - default

#  db:
#    security_opt: ["label=disable"]
#    image: mariadb:lts-ubi9
#    environment:
#      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
#      MARIADB_USER: web
#      MARIADB_PASSWORD_FILE: /run/secrets/db_password
#      MARIADB_DATABASE: snippetbox
#      MARIADB_LOG_WARNINGS: 0
#    healthcheck:
#      test: ["CMD-SHELL", "mariadb-admin ping --silent"]
#      interval: 5s
#      retries: 5
#      start_period: 30s
#    volumes:
#      - ./compose/sql/:/docker-entrypoint-initdb.d:Z
#      - db_data:/var/lib/mysql
#    secrets:
#      - db_password
#      - db_root_password
#    ports:
#      - "127.0.0.1:3306:3306"
#    networks:
#      - default

  postgres:
    security_opt: ["label=disable"]
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: web
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: clonebox
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U web -d clonebox"]
      interval: 5s
      retries: 5
      start_period: 30s
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./compose/sql/:/docker-entrypoint-initdb.d
    secrets:
      - db_password
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - default

  proxy:
    image: caddy:2.9
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./compose/caddy:/etc/caddy/:z
    networks:
      - default

secrets:
  db_password:
    file: ./compose/secrets/db_password
  db_root_password:
    file: ./compose/secrets/db_root_password
  web_llm_api_key:
    file: ./compose/secrets/web_llm_api_key

volumes:
  db_data:
  web_fileShare:

networks:
  default:
    enable_ipv6: true