services:
  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_NAME: snippetbox
      DB_USER: web
      DB_PASS: /run/secrets/db_root_password
    secrets:
      - db_password

  db:
    image: mariadb:10
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MARIADB_USER: web
      MARIADB_PASSWORD_FILE: /run/secrets/db_password
      MARIADB_DATABASE: snippetbox
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 --silent"]
      interval: 1m
      retries: 5
      start_period: 30s
    volumes:
      - ./compose/sql/:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    secrets:
      - db_password
      - db_root_password
    # ports:
    #   - "3306:3306"

  proxy:
    image: caddy:2.9
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./compose/Caddyfile:/etc/caddy/Caddyfile

secrets:
  db_password:
    file: ./compose/secrets/db_password
  db_root_password:
    file: ./compose/secrets/db_root_password

volumes:
  db_data: