services:
  web:
    build:
      context: .
      dockerfile: dockerfile.test
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_NAME: snippetbox
      DB_USER: web
      DB_PASS: /run/secrets/db_password
    secrets:
      - db_password
    ports:
      - "2345:2345"
      - "4000:4000"
    volumes:
      - web_fileShare:/clonebox/uploads
    security_opt:
      - "seccomp:unconfined"
      - "label=disable"
    cap_add:
      - SYS_PTRACE
    command: ["/go/bin/dlv", "exec", "/app/web", "--headless", "--listen=:2345", "--api-version=2", "--accept-multiclient", "--continue", "--", "-debug"]