services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_NAME: clonebox
      DB_USER: web
    secrets:
      - db_password
      - web_llm_api_key
    volumes:
      - web_fileShare:/clonebox/uploads
      - ./compose/secrets/web_llm_api_key:/run/secrets/web_llm_api_key:ro,Z
      - ./compose/secrets/db_password:/run/secrets/db_password:ro,z
    networks:
      - default

  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: web
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: clonebox
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U web -d clonebox"]
      interval: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./compose/sql/:/docker-entrypoint-initdb.d:ro,Z
      - ./compose/secrets/db_password:/run/secrets/db_password:ro,z
    secrets:
      - db_password
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - default

  proxy:
    image: caddy:2.9
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./compose/caddy:/etc/caddy/:Z
    networks:
      - default

secrets:
  db_password:
    file: ./compose/secrets/db_password
  db_root_password:
    file: ./compose/secrets/db_root_password
  web_llm_api_key:
    file: ./compose/secrets/web_llm_api_key

volumes:
  db_data:
  web_fileShare:

networks:
  default:
    enable_ipv6: true