FROM golang:1.24-alpine AS build-stage

WORKDIR /app

COPY go.mod go.sum .
RUN go mod download

RUN go install github.com/go-delve/delve/cmd/dlv@latest

COPY . .

# RUN go build -o /app/ ./cmd/web
RUN go build -gcflags="all=-N -l" -o /app/ ./cmd/web

CMD ["/app/web"]
# CMD ["/dlv", "--listen=:2345", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "/app/web"]
