package main

import (
	"bytes"
	"io"
	"net/http"
	"net/http/httptest"
	"snippetbox/internal/assert"
	"testing"
)

func TestPing(t *testing.T) {
	// Initialize a new http.ResponseRecorder
	responseRecorder := httptest.NewRecorder()

	// Initialize a dummy http.Request
	request, err := http.NewRequest(http.MethodGet, "/", nil)
	if err != nil {
		t.Fatal(err)
	}

	// Call the ping handler function, passing in the http.ResponseRecorder to get the http.Resposne generated by the ping handler
	ping(responseRecorder, request)

	// Call the Result() method on the http.ResponseRecorder to get the http.Response generated by the ping handler
	responseResult := responseRecorder.Result()

	// Check that the status code written by the ping handler was 200
	assert.Equal(t, responseResult.StatusCode, http.StatusOK)

	// And we can check that the response body written by the ping handler equals "OK"
	defer responseResult.Body.Close()
	body, err := io.ReadAll(responseResult.Body)
	if err != nil {
		t.Fatal(err)
	}
	bytes.TrimSpace(body)

	assert.Equal(t, string(body), "OK")
}
